name: tarballs
on:
  workflow_dispatch:
    inputs:
      commit: 
        description: "ziglang/zig master branch commit to build"
        required: true
        default: 'HEAD'
        type: string
#  schedule:
#    - cron: '0 */12 * * *'
jobs:
  build:
    runs-on: [self-hosted, tarballs, x86_64]
    env: 
      COMMIT: ${{ inputs.commit || 'HEAD' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Tarballs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bash .github/workflows/build-tarballs.sh