name: tarballs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: [self-hosted, tarballs, x86_64]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Tarballs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "$(pwd)"
        # run: sh .github/workflows/build-tarballs.sh