name: CI
on:
  push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code 
      uses: actions/checkout@v2

    - name: Run build setup script
      run: sh ./.github/workflows/build.sh

    - name: Build the website
      run: hugo  --minify --cleanDestinationDir

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: sh ./.github/workflows/deploy.sh
