name: Build Tarballs
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'
concurrency:
  group: tarball
jobs:
  create_tarballs:
    outputs:
      skipped: ${{ steps.build.skipped }}
    runs-on: [self-hosted, tarballs, x86_64]
    env: 
      COMMIT: ${{ inputs.commit || 'HEAD' }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Tarballs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bash .github/workflows/build-tarballs.sh
      - name: Set Ouptut
        id: build
        run: |
          echo "skipped=$SKIPPED" >> $GITHUB_OUTPUT
          echo "skipped=$SKIPPED"
        
  show_result:
      needs: create_tarballs
      runs-on: ubuntu-latest
      steps:
        - name: Print outcome
          run: echo ${{ needs.create_tarballs.outputs.skipped }}
  deploy_website:
    if: ${{ needs.create_tarballs.outputs.skipped == 'yes' }}
    needs: create_tarballs
    uses: ./.github/workflows/deploy.yml
    with:
      ref: "master"
    secrets: inherit
