name: Build Tarballs
on:
  schedule:
    - cron: '0 */6 * * *'
concurrency:
  group: tarball
jobs:
  create_tarballs:
    outputs:
      skipped: ${{ steps.build.outputs.skipped }}
    runs-on: [self-hosted, tarballs, x86_64]
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Tarballs
        id: build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./.github/workflows/build-tarballs.sh
  deploy_website:
    if: ${{ needs.create_tarballs.outputs.skipped != 'yes' }}
    needs: create_tarballs
    uses: ./.github/workflows/deploy.yml
    with:
      ref: "master"
    secrets: inherit
