name: tarballs
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'
concurrency:
  group: tarball
jobs:
  build:
    runs-on: [self-hosted, tarballs, x86_64]
    env: 
      COMMIT: ${{ inputs.commit || 'HEAD' }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build Tarballs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bash .github/workflows/build-tarballs.sh